apiVersion: v1
kind: Pod
metadata:
  name: maintainer-filestore
  labels:
    app: maintainer-filestore
spec:
  {{- if .Values.filestore.initFileDirsEnabled }}
  initContainers:
    - name: init-file-dir
      image: busybox:stable
      command:
        - sh
        - -c
        - |
          {{- range .Values.filestore.initFileDirs }}
          mkdir -p /filestore/{{ $.Values.envFile }}/{{ . }}
          {{- end }}
      volumeMounts:
        - name: filestore-volume
          mountPath: /filestore
  {{- end }}
  containers:
    - name: maintainer-container
      image: busybox:stable
      command:
        - sh
        - -c
        - echo "Main container running" && sleep infinity
      volumeMounts:
        - name: filestore-volume
          mountPath: /filestore
  volumes:
    - name: filestore-volume
      persistentVolumeClaim:
        claimName: filestore-volume-claim