bases:
  - environments.yaml

# 本機電腦下載 kafka-ui 的 helm chart repo
repositories:
  - name: kafka-ui
    url: https://provectus.github.io/kafka-ui-charts

templates:
  kafka-ui: &kafka-ui
    chart: kafka-ui/kafka-ui
    version: 0.7.6
    namespace: kafka-ui

  aws-msk-testing: &aws-msk-testing
    chart: ./aws-msk-testing
    version: 0.1.0
    namespace: test

  gke-network-filestore-system-controller: &gke-network-filestore-system-controller
    chart: ./gke-network-filestore-system-controller
    version: 0.1.0
    namespace: test
    values:
      - apps/gke-filestore-system-controller/{{`{{ .Environment.Name }}`}}.yaml

releases:
  - name: kafka-ui
    <<: *kafka-ui
    values:
      - apps/kafka-ui/values.yaml

  - name: aws-msk-testing
    <<: *aws-msk-testing
    values:
      - apps/aws-msk-testing/values.yaml

  - name: gke-filestore-system-controller
    <<: *gke-network-filestore-system-controller
