apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  containers:
    - name: kafka-producer
      image: apache/kafka:3.7.0
      workingDir: /opt/kafka/bin
      command: ./kafka-topics.sh --create --topic {{ .Values.topic }} --bootstrap-server {{ .Values.bootstrapServer }}
      env:
        - name: bootstrapServer
          value: {{ .Values.bootstrapServer }}
        - name: topic
          value: {{ .Values.topic }}